### PR TITLE
Edit pa refactor

### PR DESCRIPTION
**Pull request by jepidoptera**
Lots to review here. A good starting point might be making sure that the tests are sensible and comprehensive

### CODE REVIEW

**Comment by poliwop** [comment]
Seeing the degree of restructuring of the objects is making me wonder about performance... Have you run any performance tests before/after the refactor? Even simple timing of a simulation with enough trades/paths to take a bit of time? It would probably be good to do that. Doesn't necessarily have to block merging this but it may then become a priority to improve, if this refactoring hurts performance at all.

**Comment by poliwop** [comment]
I'm seeing that this refactor appears to go heavily against functional program which I'm a little concerned about... if we merge this up as-is I'm going to ask that we make it a top priority to fix this in a next iteration. Shared mutable state is extremely difficult to scale, the complexities are a challenge to maintain.

**Comment by jepidoptera** [comment]
> First note is that neither test_omnipool_amm.py nor test_amm.py work. Are these not expected to work, in favor of the new test_modular_amm.py? If so we should remove them.
> 
> Or better yet, probably rename test_modular_amm.py to test_amm (if separating tests into two files no longer makes sense?)
> 
> I'm a little surprised it no longer makes sense to separate into the AMM math versus the API, but I haven't dug too much yet so I will see...

Those aren't expected to work, and I have actually since deleted them. Rename makes sense, and it's possible that it still does make sense to separate into two test files.

**Comment by jepidoptera** [comment]
> Seeing the degree of restructuring of the objects is making me wonder about performance... Have you run any performance tests before/after the refactor? Even simple timing of a simulation with enough trades/paths to take a bit of time? It would probably be good to do that. Doesn't necessarily have to block merging this but it may then become a priority to improve, if this refactoring hurts performance at all.

My really basic "benchmarking" (running testIL notebooks side-by-side with a stopwatch) shows that the new version is significantly faster (17 seconds vs 22).

**Comment by jepidoptera** [comment]
> 

Right. The idea, I think, is to have this WorldState object, which is copied and then mutated at every iteration... And I think that concept is not consistently implemented at the moment. I can work on cleaning that up.

**Comment by poliwop** [comment]
Ah okay, as long as you are on board with that philosophy I would not worry about getting it all fixed before the merge. I just see a lot of classes that are built that are going to need to be refactored because they are *designed* to be mutated.

**Comment by poliwop** [comment]
Broadly I think the changes I'd request would be for the classes to behave like structs, possibly with inheritance providing a form of "interface" (i.e. shared interface between different structs).

I would say that the classes should not have methods at all, and the intended way of interacting with them should not involve mutating them. I think this will basically involve moving functions outside the class, adding an object input, and then for functions which process a state change, returning *new* objects with the new state(s).

Thoughts on this?

**Pull request closed without merging**
