### PR TITLE
Edit pa readme

### PR DESCRIPTION
**Pull request by jepidoptera**

### CODE REVIEW

**Comment by poliwop** [comment]
@jepidoptera is there a github ticket associated with this PR?

**Comment by poliwop** [comment]
I am assuming this is for issue #61?

**Comment by jepidoptera** [comment]
Yes, I marked it

**Comment by poliwop** [comment]
Merging up, got a new virtual environment installed & working from this. I do think we need to also specify instructions on how to use the venv with Jupyter, which is something I haven't yet figured out.

**Pull request merged**
